dist: xenial
language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
services:
- docker
install:
- pip install -U -r requirements-dev.txt
- pip install -r requirements.txt
env:
  global:
  - PYPI_USER_NAME: chaosiq
  - secure: ak3MR0Opnv9fNOtQNGP1WtaFqWmRlpjTOiVNZMZ+Ihk+FE4pYvxLkfURs/BUII17Rb5KevGzi5cQvF4kYDqVo4i3+uppJqfCxBEMd/Nhh3hbi7zU/Cak0kfa5Xrggd0gGzUiFbsWEUOK1146DZwEZ8yuclDtBu8wix0n53xPCmmsHwFqM8WoUSwwUhyaT45mZC3sqEenNV/xNYjBOA55ESRPRDw6H8EW1sz+oEvu/7VppPUS4ADXMqgcwY9qLcpJcdGffa7QN2ydxvFcxXilYqm35PN3sjednibqzg0FzzogYMLnIiAphOgnDvJ2UkfUyUgyTFUhoI1p8R4PsVsgkayOo3v5fui0uzt4ewEolxYNR5X4dKGBdlckeRXnavkZ1X75Zebc9xw/b1EhmeG+BcSTZJ8YBxU2Yr1DZJPSAzNr5tWpTDICXziHepsXmihPjPvjThLtRDfO9Da32GZOIWVWXng3WPCCVrPmK2uOK2tfRHAFsnT2HcUKvBo01SFH0wsE4gXr8Rw537Wgv+sflkn0fGkeR4Mlv2Er63wKfNLbXlog4xj5KS5jIFaU7dAa7rH/PEb5bGgKeKkXLmn1WYHR+JrN2h1EI791m9HSQTdt9L+Bw1ZuXWuD5ODi65fp1QdyS5vz3vHT2lc09AIN1JDGxKWY70vq7aschdWJph4=
  - DOCKER_USER_NAME: chaosiq
  - secure: mX+/ts3PCV+bEX13hhJe6Lx7UYZwB1wqqBGj4Tp1ca9/0NZgLSoqLySz2YxahcX9633F9045AQR+sKx9tzg4iywW5Yijj+nQ0KlbpTK5JrbkY2Z1i/Ge18UmBSydQZ8lJRmFkODzJhkNcxS0QQJF3rPSb0oylkoM0hzzL68096E07q0PUU2SJx046XL6745QK0vNx8ebqwQncrM/A4jXATyo+BAKQjHS1HHjRRRj4unZjQkez7dZsnB0YVWyrJlH9pmGVkuvDYrh4Gob0ROL7b2oFyPjaECwdO9dsiKbaVbcN33yvPlT8ah9e8mDpyWFAID9PZZiEPNb3BcSDwt7l+A1zLpKtgrTW/NBuPnHYuYANyEESsZVkNSlcl3nA9VK5nXDFj53aPFblYEzXJHkKmCfQVO6CY+/98i7NO4YeIyjbBJypVxeds3fCEPsYd9SXpgV1ArFQ6PFKzg5FR+hbPHi2SivRl8q2DTpVitHMrofAbk1VDWpkPCwJN1yqnhs3SLLOMouwoMUjA/EfWwZCZeL8xWzKJvWpZ21M+ZDwg2MU//r+L51QCN7NYsXlnhFpnUYtc4SVCZwAQgAl/vb8dm6qE4123s/vN8RgaHXgZUW2cHjqDXmpyNBfyRMXGPbtzXw0Ds1WDcIfUlzh3KUQ8+1OrqQzhc7LlYfpjX7+/M=

script:
- bash ci.bash
notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
